apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: hashicorp/http-echo:latest
          args:
            - "-text=Hello from Karpenter node!"
          ports:
            - containerPort: 5678
          resources:
            # Instead of 1 big pod (1 vCPU, 2Gi RAM)
            # More replicas improve resilience: If one pod fails, the service still runs.
            # Better load balancing: Spreading requests across multiple pods can reduce bottlenecks.
            requests:
              cpu: "0.5"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: inflate
spec:
  selector:
    app: inflate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
